import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import getServerDarkMode from "@/hooks/user-server-dark-mode";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template: "%s | Finance App",
    default: "Finance App",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const theme = await getServerDarkMode();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${theme}`}
    >
      <body className="min-h-full flex flex-col px-8">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
